# Generated by Django 3.2.9 on 2021-11-13 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title', 'id'])),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('county', models.CharField(choices=[('Zagrebačka', 'Zagrebačka'), ('Krapinsko_zagorska', 'Krapinsko-zagorska'), ('Sisačko_moslavačka', 'Sisačko-moslavačka'), ('Karlovačka', 'Karlovačka'), ('Varaždinska', 'Varaždinska'), ('Koprivničko_križevačka', 'Koprivničko-križevačka'), ('Bjelovarsko_bilogorska', 'Bjelovarsko-bilogorska'), ('Primorsko_goranska', 'Primorsko-goranska'), ('Ličko_senjska', 'Ličko-senjska'), ('Virovitičko_podravska', 'Virovitičko-podravska'), ('Požeško_slavonska', 'Požeško-slavonska'), ('Brodsko_posavska', 'Brodsko-posavska'), ('Zadarska', 'Zadarska'), ('Osječko_baranjska', 'Osječko-baranjska'), ('Šibensko_kninska', 'Šibensko-kninska'), ('Vukovarsko_srijemska', 'Vukovarsko-srijemska'), ('Splitsko_dalmatinska', 'Splitsko-dalmatinska'), ('Istarska', 'Istarska'), ('Dubrovačko_neretvanska', 'Dubrovačko-neretvanska'), ('Međimurska', 'Međimurska'), ('Grad_Zagreb', 'Grad Zagreb')], max_length=50)),
                ('area', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('car_spaces', models.PositiveIntegerField()),
                ('property_type', models.CharField(choices=[('Stan', 'Stan'), ('Kuća', 'Kuća'), ('Apartman', 'Apartman'), ('Poslovni_prostor', 'Poslovni prostor')], max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
